your_age = int(input("Please tell me your age : "))
print (f"You are currently {your_age} years old." )
print(f"In 10 years, you'll be {your_age +10} years old. ")
print(f"In 20 years, you'll be {your_age + 20} years old. ")
print(f"In 30 years, you'll be {your_age + 30} years old.")
